### ISSUE TITLE
Remove fixed IV example, may be mistakenly perpetuated by beginners

### ISSUE THREAD

**Issue by silviuk** [sebsto/kms-demo#1]
https://github.com/sebsto/kms-demo/blob/8547db67a16b77f53503c888b0609eefa88d9e3f/main.py#L35

**Comment by silviuk** [comment]
The other one with random IV below is preferable. In fact, one might want to totally take away IV generation from user's hands in such high-level crypto APIs...
https://github.com/sebsto/kms-demo/blob/8547db67a16b77f53503c888b0609eefa88d9e3f/main.py#L108

**Comment by sebsto** [comment]
Fixed with https://github.com/sebsto/kms-demo/commit/9e11cfe4f55969a1d6e6c45ec03186bb8081c993 

Thank you
